version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8080 WebUI.asgi:application"
    volumes:
      - ./user_data:/app/user_data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8080"
    environment:
      - DJANGO_SETTINGS_MODULE=WebUI.settings
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles:ro
      - ./user_data:/app/user_data:ro
    ports:
      - "8080:8080"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data: